Game and author  functionality
monicah79/Capstone-ruby pull request #32
Opened 2023-04-14 09:27 UTC by AbdifatahYasin1

### Game and author  functionality

- Create Author class
- Implement methods in Game & Author class
- Add unit tests for Author and Game classes
  and so on

2023-04-14 09:28 UTC, AbdifatahYasin1 commented
@MNisarAli please help me to fix that linter errors

2023-04-14 15:15 UTC, MNisarAli commented
> @MNisarAli please help me to fix the linter errors and also the game test

Hi @AbdifatahYasin1, To fix the rubocop lint errors follow these steps:

1. Method has too many lines:

- app.rb:11:3: C: Metrics/MethodLength: Method has too many lines. [31/20]
- game_author.rb:99:3: C: Metrics/MethodLength: Method has too many lines. [40/20]
- [ ] **Solution:** You can break down the code into smaller methods, each with a specific responsibility to reduce the number of lines in the methods.

2. Final newline missing:

- author.rb:50:4: C: [Correctable] Layout/TrailingEmptyLines: Final newline missing.
- game.rb:46:4: C: [Correctable] Layout/TrailingEmptyLines: Final newline missing.
- game_author.rb:141:4: C: [Correctable] Layout/TrailingEmptyLines: Final newline missing.
- genre.rb:17:4: C: [Correctable] Layout/TrailingEmptyLines: Final newline missing.
- item.rb:34:4: C: [Correctable] Layout/TrailingEmptyLines: Final newline missing.
- main.rb:7:4: C: [Correctable] Layout/TrailingEmptyLines: Final newline missing.
- spec/author_spec.rb:31:4: C: [Correctable] Layout/TrailingEmptyLines: Final newline missing.
- [ ] **Solution:** You can add a final newline at the end of each file to resolve this error.

3. Block has too many lines:

- game_author.rb:101:5: C: Metrics/BlockLength: Block has too many lines. [37/30]
- [ ] **Solution**: You can extract the inner loop to a separate method and call that method from the loop to reduce the number of lines.

2023-04-14 15:31 UTC, MNisarAli requested changes
## Status: Changes Required ♻️

Hi 👋, @AbdifatahYasin1 Great job so far! 👏🏻
The methods are doing their job nicely. However, you still have some changes to make before you merge this branch. 

**Kindly look through the comments below 👇**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

------
Cheers 🥂  and Happy coding!!!
**Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @MNisarAli in your question so I can receive the notification.**

2023-04-15 04:17 UTC, MNisarAli approved these changes

2023-04-15 04:18 UTC, merged